export const CART_REQUEST = 'CART_REQUEST';
export const CART_SUCCESS = 'CART_SUCCESS';
export const CART_FAIL = 'CART_FAIL';
export const CART_RESET = 'CART_RESET';
export const CART_ADD_ITEM = 'CART_ADD_ITEM';

export const CART_ADD_ITEM_REQUEST = 'CART_ADD_ITEM_REQUEST';
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL';
export const CART_ADD_ITEM_SUCCES = 'CART_ADD_ITEM_SUCCES';
export const CART_ADD_ITEM_RESET = 'CART_ADD_ITEM_RESET';

