export const IMAGE_ADD_IMAGE_REQUEST = 'IMAGE_ADD_IMAGE_REQUEST';
export const IMAGE_ADD_IMAGE_SUCCESS = 'IMAGE_ADD_IMAGE_SUCCESS';
export const IMAGE_ADD_IMAGE_FAIL = 'IMAGE_ADD_IMAGE_SUCCESS';
export const IMAGE_ADD_IMAGE_RESET = 'IMAGE_ADD_IMAGE_RESET';
