export const RATING_CREATE_REQUEST = 'RATING_CREATE_REQUEST';
export const RATING_CREATE_SUCCES = 'RATING_CREATE_SUCCES';
export const RATING_CREATE_FAIL = 'RATING_CREATE_FAIL';
export const RATING_CREATE_RESET = 'RATING_CREATE_RESET';
